### PR TITLE
[FEATURE] makes loadbalancers optional 

### PR DESCRIPTION
**Pull request by dloiacono**

### CODE REVIEW

**Comment by dloiacono** [comment]
you mean kubernetes annotations on the kubernetes services?
Could you past an example?

**Comment by asafchen-dig** [comment]
Exactly, please see the values files under this folder:
https://github.com/digma-ai/helm-chart/tree/main/src/digma-configs

**Comment by dloiacono** [comment]
what about private cloud? I don't see specific yml

**Review by asafchen-dig — APPROVED** [review]

**Comment by asafchen-dig** [comment]
@dloiacono we have only values files for eks and gks
What private cloud are you using?

**Comment by dloiacono** [comment]
@asafchen-dig we are using k8s provided OpenStack  https://www.openstack.org/

**Comment by dloiacono** [comment]
are the proposed changes so dangerous form your point of view?
Why do you still have doubts?

**Comment by asafchen-dig** [comment]
@dloiacono we added those changes in another pr #209
I'm closing this one

**Pull request closed without merging**
